export default function Head() {
  return (
    <>
      <title>Grishaverse</title>
      <link rel="icon" href="/grishaverse.webp" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="minimum-scale=1, initial-scale=1, width=device-width"
      />
    </>
  )
}
